export const tempData = [
  {author: 'Klaus Teuber',
    authorId: 1,
    id: 1,
    title: 'Catan',
    description: `Osadnicy z Catanu (Settlers of Catan) to bardzo popularna na całym świecie gra rodzinno-ekonomiczna o bardzo dużej "miodności" grania. Teraz prezentujemy jej polską edycję!

    Gracze są osadnikami na niedawno odkrytej wyspie Catan. Każdy z nich przewodzi świeżo założonej kolonii i rozbudowuje ją stawiając na dostępnych obszarach nowe drogi i miasta. Każda kolonia zbiera dostępne dobra naturalne, które są niezbędne do rozbudowy osiedli.
    
    Gracz musi rozważnie stawiać nowe osiedla i drogi, aby zapewnić sobie dostateczny, ale zrównoważony dopływ zasobów, a jeśli ma ich nadmiar - prowadzić handel z innymi graczami sprzedając im owce, drewno, cegły, zboże lub żelazo a pozyskując od nich te zasoby, których ciągle mu brakuje.
    
    Pierwszy z graczy, który uzyska dziesięć punktów z wybudowanych przez siebie dróg, osiedli i specjalnych kart - wygrywa.`,
    photo: '',
    language: 'polish',
    yearOfRelease: 1995,
    publishingHouse: 'Galakta',
    type: 'BoardGame',
    owner: 'Dominik Tracz',
    ownerId: 1,
    shelfId: 1,
    isPrivate: false,
    
    minPlayers: 3,
    maxPlayers: 4,
    length: '1h',
    minAge: 10,
    
    isBorrowed: false,
    isToLet: true,
    borrower: '',
    borrowerId: 0,
  }, {author: 'Jacob Fryxelius',
    authorId: 2,
    id: 2,
    title: 'Terraformacja Marsa',
    description: `Ludzkość rozpoczęła ekspansję w Układzie Słonecznym. Na Marsie założono już kilka niewielkich kolonii. Ich mieszkańcy są odgrodzeni od naturalnego środowiska straszliwie zimnej, suchej i niemal pozbawionej atmosfery planety.

    Zwiększenie odsetka imigracji z Ziemi wymaga terraformacji Marsa, czyli dostosowania jego środowiska, aby ludzie mogli w nim przeżyć bez sprzętu ochronnego i aby zminimalizować śmiertelność w wyniku drobnych wypadków. W związku z tym Rząd Ziemi zdecydował się wesprzeć każdą organizację, która przyczyni się do tego wiekopomnego dzieła.
    
    Hojne dofinansowanie przyciąga gigantyczne korporacje, które pragną zwiększyć swój udział w rynku i stać się najbardziej wpływowymi podmiotami realizującymi projekt terraformacji. Ujarzmienie Czerwonej Planety to dla wielu szansa na oszałamiający sukces.`,
    photo: '',
    language: 'polish',
    yearOfRelease: 2015,
    publishingHouse: 'Rebel',
    type: 'BoardGame',
    owner: 'Damian Sowiński',
    ownerId: 2,
    shelfId: 2,
    isPrivate: false,
    
    minPlayers: 1,
    maxPlayers: 5,
    length: '2h',
    minAge: 12,
    
    isBorrowed: false,
    isToLet: true,
    borrower: '',
    borrowerId: 0,
  }, {author: 'Brandon Sanderson',
    authorId: 3,
    id: 3,
    title: 'Dawca Przysięgi',
    description: `W „Dawcy Przysięgi”, trzecim tomie bestsellerowego Archiwum Burzowego Światła, ludzkość musi stawić czoło nowemu Spustoszeniu i powrotowi Pustkowców – wroga, którego liczebność jest równie wielka, jak pragnienie zemsty.`,
    photo: '',
    language: 'polish',
    yearOfRelease: 2017,
    publishingHouse: 'Mag',
    type: 'Book',
    owner: 'Dominik Tracz',
    ownerId: 1,
    shelfId: 1,
    isPrivate: false,
    
    pages: 640,
  
    isBorrowed: false,
    isToLet: true,
    borrower: '',
    borrowerId: 0,
  }, {author: 'Lewis C.S',
    authorId: 4,
    id: 4,
    title: 'Opowieści z Narnii. Tom 1, Lew, Czarownica i Stara Szafa.',
    description: `W marzeniach, snach i w Twojej wyobraźni kryje się klucz do nieznanego świata. Książka C.S. Lewisa to opowieść, która poruszy umysłowość czytelnika, uwrażliwi go i otworzy na świat fantazji.

    Akcja pierwszego tomu „Opowieści z Narnii” rozgrywa się w niezwykłej, skutej lodem krainie. Czworo śmiałków wkracza do niej przez drzwi starej szafy, aby przeciwstawić się mocy Białej Czarownicy. Z kim będziesz się utożsamiał podczas lektury książki „Lew, czarownica i stara szafa”? Z małą Łucją, która w starym meblu dostrzegła coś więcej niż tylko szafę z futrami czy może z niedowierzającym jej Edmundem? Są jeszcze Piotr i Zuzanna, którzy wspólnie wypełniają proroctwo i zasiadają na poczwórnym tronie Narnii.`,
    photo: '',
    language: 'polish',
    yearOfRelease: 2005,
    publishingHouse: 'Media Rodzina',
    type: 'Book',
    owner: 'Magdalena Tracz',
    ownerId: 3,
    shelfId: 1,
    isPrivate: false,
    
    pages: 182,
  
    isBorrowed: false,
    isToLet: true,
    borrower: '',
    borrowerId: 0,
  }, {author: 'Klaus-Jurgen Wrede',
  authorId: 5,
  id: 5,
  title: 'Carcassonne',
  description: `Usiądź z przyjaciółmi przy stole i wspólnie zacznijcie budować z niewielkich żetonów łąki, twierdze, całe miasta i drogi, rywalizując między sobą o przejęcie kontroli nad co bardziej atrakcyjnymi lokacjami.
    Sprytne zagranie może pozbawić rywala możliwości ukończenia ogromnego miasta lub pozwoli Ci przejąć kontrolę nad wielką łąką.`,
  photo: '',
  language: 'polish',
  yearOfRelease: 2011,
  publishingHouse: 'Bard',
  type: 'BoardGame',
  owner: 'Dominik Tracz',
  ownerId: 1,
  shelfId: 1,
  isPrivate: false,
  
  minPlayers: 2,
  maxPlayers: 5,
  length: '30 min',
  minAge: 7,
  
  isBorrowed: false,
  isToLet: true,
  borrower: '',
  borrowerId: 0,
  }, {author: 'Brandon Sanderson',
authorId: 3,
id: 6,
title: 'Droga Królów',
description: `Tęsknię za dniami przed Ostatnim Spustoszeniem. Epoką, zanim Heroldowie nas porzucili, a Świetliści Rycerze zwrócili się przeciwko nam. Czasem, gdy na świecie wciąż była magia, a w sercach ludzi był honor.`,
photo: '',
language: 'polish',
yearOfRelease: 2014,
publishingHouse: 'Mag',
type: 'Book',
owner: 'Dominik Tracz',
ownerId: 1,
shelfId: 1,
isPrivate: false,

pages: 1136,

isBorrowed: false,
isToLet: true,
borrower: '',
borrowerId: 0,
},
]